/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Alumno
 */




public class frmCalculadora extends javax.swing.JFrame {
    
    private void limpiarCampos(){
        texkg.setText("");
        texal.setText("");
        teximc.setText("");
        texre.setText("");
    }
 
    /**
     * Creates new form frmCalculadora
     */
    public frmCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        texkg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texal = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        teximc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Peso en Kilogramos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        texkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texkgActionPerformed(evt);
            }
        });
        getContentPane().add(texkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, -1));

        jLabel2.setText("Calculadora de IMC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel3.setText("Altura: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(texal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 70, -1));

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel4.setText("IMC=");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(teximc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 230, -1));

        jLabel5.setText("Resultado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(texre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texkgActionPerformed
        
    }//GEN-LAST:event_texkgActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_borrarActionPerformed

    Double peso, altura, imc;
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        peso = Double.parseDouble(texkg.getText());
        altura = Double.parseDouble(texal.getText());
        CalcularIMC(altura,peso);
        resultado();
    }//GEN-LAST:event_calcularActionPerformed

    private void resultado(){
        if(imc<=18.5){
           texre.setText("Peso inferior al normal");
        }
        
        if ((imc >=18.6) || (imc <= 24.9)){
            texre.setText("Normal Chaval");
        }
        
        if ((imc >= 25) || (imc <= 29.9)){
            texre.setText("Peso superior al normal");
        }
        
        if (imc >=30){
            texre.setText("Obeso gordo :v");
        }
    }
    private void CalcularIMC(double altura, double peso){
        imc= peso / (altura * altura);
        teximc.setText(String.valueOf(imc));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField texal;
    private javax.swing.JTextField teximc;
    private javax.swing.JTextField texkg;
    private javax.swing.JTextField texre;
    // End of variables declaration//GEN-END:variables
}
